### ISSUE TITLE
Lume v3 and deno 2.2.7 breaks sharp

### ISSUE THREAD

**Issue by RickCogley** [lumeland/lume#743]
### Version

df455270751a58beab87aac2f27f8820d24e3baf

### Platform

MacOS

### What steps will reproduce the bug?

Use "dvm" to:
dvm upgrade
dvm use latest
... which upgrades to 2.2.7

Upgrade to latest lume v3 dev

Run with `lume cms` and it fails with a sharp error

```
❯ lume cms
Task lume echo "import 'lume/cli.ts'" | deno run -A - "cms"
Loading config file file:///Users/rcogley/dev/blog.esolia.pro/_config.ts
error: Uncaught (in worker "") (in promise) Error: Could not load the "sharp" module using the darwin-arm64 runtime
undefined: dlopen(/Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/@img/sharp-darwin-arm64/0.33.5/lib/sharp-darwin-arm64.node, 0x0001): symbol not found in flat namespace '_napi_create_error'
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.33.5/lib/sharp.js:113:9)
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.33.5/lib/sharp.js:116:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:816:16)
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.33.5/lib/constructor.js:10:1)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:178:7)
❯ 
```

### How often does it reproduce? Is there a required condition?

consistent, tried deleting _site, _cache, and it's the same

reverting to deno 2.2.6 (`dvm use 2.2.6`) fixes 

### What is the expected behavior?

not dying with sharp using latest deno

### What do you see instead?

that it works with 2.2.7

**Comment by RickCogley** [comment]
deno 2.2.6 runs latest lume dev v3 as of just now, just fine

**Comment by oscarotero** [comment]
It works fine in my end (macOS).
A new version of sharp has been released today. I just upgraded Lume 3 to use it. Can you try now?

**Comment by RickCogley** [comment]
Walking the dog but I'll try later!

**Comment by RickCogley** [comment]
ok, I tried again, switching to deno 2.2.7, and upgrading lume to latest v3, but, here is the error: 

```
❯ lume cms
Task lume echo "import 'lume/cli.ts'" | deno run -A - "cms"
Loading config file file:///Users/rcogley/dev/blog.esolia.pro/_config.ts
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:sharp@0.34.0
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
error: Uncaught (in worker "") (in promise) Error: Could not load the "sharp" module using the darwin-arm64 runtime
undefined: dlopen(/Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/@img/sharp-darwin-arm64/0.34.0/lib/sharp-darwin-arm64.node, 0x0001): symbol not found in flat namespace '_napi_create_error'
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.34.0/lib/sharp.js:121:9)
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.34.0/lib/sharp.js:124:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:816:16)
    at Object.<anonymous> (file:///Users/rcogley/Library/Caches/deno/npm/registry.npmjs.org/sharp/0.34.0/lib/constructor.js:10:1)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:178:7)
user=3.15s system=1.50s cpu=9% total=48.011

```

**Comment by RickCogley** [comment]
is deno downloading packages somewhere that I should delete, to check?

**Comment by RickCogley** [comment]
right, checking again: after upgrading lume 3 to latest, switching to deno 2.2.6 works

**Comment by oscarotero** [comment]
You can delete the Deno cache folder (you can run `deno info` to know the DENO_DIR location but seeing the error, it's `/Users/rcogley/Library/Caches/deno`).

**Comment by RickCogley** [comment]
Thanks for telling me about `deno info`! Ok, tried deleting the deno cache, then deleted _cache and _site from the project folder, and on `lume cms`, still the same error. Then I saw that deno got upgraded to 2.2.8 (it popped up while I was working on the other things), so I upgraded to that, and can confirm that that indeed works. Maybe they made an emergency patch?!

**Comment by oscarotero** [comment]
No idea (the [release changelog](https://github.com/denoland/deno/releases/tag/v2.2.8) doesn't mention anything that seems relevant, as far as I can see).

But if it works, probably something was affected.

**Comment by RickCogley** [comment]
maybe so! I feel something must have been buggy, for them to release on back-to-back days.
