### ISSUE TITLE
TypeError: Deno.spawn is not a function after upgrading Deno to 1.29 (was working in 1.28.3)

### ISSUE THREAD

**Issue by alaminkouser** [lumeland/lume#338]
### Version

1.14.1

### Platform

Windows and GitHub Page Deploy

### What steps will reproduce the bug?

1. Setup lume
2. add pagefind plugin
3. build OR run (deno task serve)

### How often does it reproduce? Is there a required condition?

Everytime

### What is the expected behavior?

Run and Build and Deploy

### What do you see instead?

```
TypeError: Deno.spawn is not a function
    at (https://deno.land/x/lume@v1.14.1/plugins/pagefind.ts:182:51)
    at async Events.dispatchEvent (https://deno.land/x/lume@v1.14.1/core/events.ts:49:11)
    at async Site.build (https://deno.land/x/lume@v1.14.1/core/site.ts:521:5)
    at async build (https://deno.land/x/lume@v1.14.1/cli/build.ts:36:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.5/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.5/command/command.ts:1639:14)
    at async (https://deno.land/x/lume@v1.14.1/cli.ts:147:3)
```

## [spawn is deprecated](https://deno.land/api@v1.28.3?unstable=&s=Deno.spawn)

**Comment by oscarotero** [comment]
Thanks for reporting this
It's fixed in v1.14.2
